### ISSUE TITLE
User Profiles and Driver Registration

### ISSUE THREAD

**Issue by NirmalAgnihotri** [TritonSE/LAK-Goods-Transport-Application#81]
Description:
- [x] We need a button in the top right of the landing page to navigate to the View Profile page. (Screenshot 1)
- [x] Users should be able to register as drivers. 
- [x] Users should also be able to edit their profile, including images.
- [x] Finally, we need to hook up image uploading to the forms (edit profile, driver registration)
  - It might be helpful to abstract some of the code from AddJob.tsx out into a common file? Up to you
  - Work for this is under page/Stuart6557/driver-registration

NOTE: See pull request #75 for viewing user and driver profiles. The PR also contains the backend functions to save and get user profile data.
Screenshot If Applicable:
<img width="324" alt="Screen Shot 2023-01-09 at 11 00 58 AM" src="https://user-images.githubusercontent.com/27360825/211386914-4bdeae0a-c1d6-4a35-a1d6-5ae531f0f12f.png">

<img width="364" alt="image" src="https://user-images.githubusercontent.com/53363382/211172765-c14e2d2f-8d3f-439a-bae7-73ad4f6f4e3c.png">
<img width="263" alt="image" src="https://user-images.githubusercontent.com/53363382/211172768-c029559b-8b2b-4109-8d9c-3a0bc29f1074.png">
